---
- hosts: localhost
  vars_files:
    - vm_vars.yaml
  
  tasks:
    - name: Prepare Volume With Backing Image
      block:
        - name: Create Backing Image
          import_role:
            name: create-backing-image
          vars:
            - pool: "{{volume.pool}}"
            - os_name: "{{volume.backing_image.name}}"
            - os_version: "{{volume.backing_image.version}}"   

        - name: Create Volume with backing image
          import_role: 
            name: create-volume
          vars: 
            - image_size: "{{volume.size}}"
            - image_format: qcow2
            - image_name: "{{name}}.qcow2"
            - pool: "{{volume.pool}}"
            - backing_vol: "{{volume.backing_image.name}}_{{volume.backing_image.version}}_cloudimage.qcow2"

      when: volume.backing_image is defined

    - name: Create VM
      block: 
        - name: Create Cloud Init VM
          import_role:
            name: create-vm-cloud-init
          vars:
            - vm_name: "{{name}}"
            - vm_dir: "{{dir}}/{{name}}"
            - vm_ram_size: "{{ram}}"
            - vm_vcpus: "{{cpus}}"
            - mgmt_if_name: "{{cloud_init.mgmt_if_name}}"
            - mgmt_if_mac: "{{cloud_init.mgmt_if_mac}}"
            - username: "{{cloud_init.username}}"
            - password: "{{cloud_init.password}}"
            - disk_pool: "{{volume.pool}}"
            - disk_name: "{{name}}.qcow2"
            - network_config_version: "{{cloud_init.network_config_version}}"
      when: cloud_init is defined